/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.AppMaster;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 앱 마스터 테이블
 *  - 여러개의 앱에서 하나의 데이터베이스를 공유하기 때문에 각각의 앱을 구분하기 위한 테이블 
 *  - 선단별로 앱을 각각 가짐
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppMasterRecord extends UpdatableRecordImpl<AppMasterRecord> implements Record7<Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1587461108;

    /**
     * Setter for <code>fishing_reservation.app_master.id</code>. 앱을 구분하기 위한 아이디
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.app_master.id</code>. 앱을 구분하기 위한 아이디
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.app_master.name</code>. 앱 이름
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.app_master.name</code>. 앱 이름
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.app_master.description</code>. 앱 상세정보
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.app_master.description</code>. 앱 상세정보
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.app_master.use_yn</code>. 사용여부
     */
    public void setUseYn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.app_master.use_yn</code>. 사용여부
     */
    public String getUseYn() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.app_master.cancel_date</code>. 취소일자 (use_yn 값이 N으로 변경시 변경된 일시를 넣어줘야 함)
     */
    public void setCancelDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.app_master.cancel_date</code>. 취소일자 (use_yn 값이 N으로 변경시 변경된 일시를 넣어줘야 함)
     */
    public LocalDateTime getCancelDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fishing_reservation.app_master.updated</code>. 수정일시
     */
    public void setUpdated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>fishing_reservation.app_master.updated</code>. 수정일시
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>fishing_reservation.app_master.created</code>. 생성일시
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>fishing_reservation.app_master.created</code>. 생성일시
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AppMaster.APP_MASTER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AppMaster.APP_MASTER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AppMaster.APP_MASTER.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return AppMaster.APP_MASTER.USE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return AppMaster.APP_MASTER.CANCEL_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return AppMaster.APP_MASTER.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return AppMaster.APP_MASTER.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getCancelDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getCancelDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppMasterRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppMasterRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppMasterRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppMasterRecord value4(String value) {
        setUseYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppMasterRecord value5(LocalDateTime value) {
        setCancelDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppMasterRecord value6(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppMasterRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppMasterRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppMasterRecord
     */
    public AppMasterRecord() {
        super(AppMaster.APP_MASTER);
    }

    /**
     * Create a detached, initialised AppMasterRecord
     */
    public AppMasterRecord(Integer id, String name, String description, String useYn, LocalDateTime cancelDate, LocalDateTime updated, LocalDateTime created) {
        super(AppMaster.APP_MASTER);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, useYn);
        set(4, cancelDate);
        set(5, updated);
        set(6, created);
    }
}
