/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.BankMaster;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BankMasterRecord extends TableRecordImpl<BankMasterRecord> implements Record8<Integer, Integer, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -408096189;

    /**
     * Setter for <code>fishing_reservation.bank_master.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.bank_master.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.bank_master.app_id</code>.
     */
    public void setAppId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.bank_master.app_id</code>.
     */
    public Integer getAppId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.bank_master.bank_name</code>.
     */
    public void setBankName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.bank_master.bank_name</code>.
     */
    public String getBankName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.bank_master.account_no</code>.
     */
    public void setAccountNo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.bank_master.account_no</code>.
     */
    public String getAccountNo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.bank_master.user_name</code>.
     */
    public void setUserName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.bank_master.user_name</code>.
     */
    public String getUserName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fishing_reservation.bank_master.use_yn</code>.
     */
    public void setUseYn(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fishing_reservation.bank_master.use_yn</code>.
     */
    public String getUseYn() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fishing_reservation.bank_master.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>fishing_reservation.bank_master.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>fishing_reservation.bank_master.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>fishing_reservation.bank_master.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BankMaster.BANK_MASTER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return BankMaster.BANK_MASTER.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BankMaster.BANK_MASTER.BANK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BankMaster.BANK_MASTER.ACCOUNT_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BankMaster.BANK_MASTER.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BankMaster.BANK_MASTER.USE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return BankMaster.BANK_MASTER.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return BankMaster.BANK_MASTER.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBankName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAccountNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBankName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAccountNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankMasterRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankMasterRecord value2(Integer value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankMasterRecord value3(String value) {
        setBankName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankMasterRecord value4(String value) {
        setAccountNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankMasterRecord value5(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankMasterRecord value6(String value) {
        setUseYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankMasterRecord value7(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankMasterRecord value8(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BankMasterRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BankMasterRecord
     */
    public BankMasterRecord() {
        super(BankMaster.BANK_MASTER);
    }

    /**
     * Create a detached, initialised BankMasterRecord
     */
    public BankMasterRecord(Integer id, Integer appId, String bankName, String accountNo, String userName, String useYn, LocalDateTime updated, LocalDateTime created) {
        super(BankMaster.BANK_MASTER);

        set(0, id);
        set(1, appId);
        set(2, bankName);
        set(3, accountNo);
        set(4, userName);
        set(5, useYn);
        set(6, updated);
        set(7, created);
    }
}
