/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.CommunityComment;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;


/**
 * 커뮤니티 댓글
 *  - 현재 사용안함
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommunityCommentRecord extends TableRecordImpl<CommunityCommentRecord> implements Record5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -185981953;

    /**
     * Setter for <code>fishing_reservation.community_comment.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_comment.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.community_comment.uid</code>.
     */
    public void setUid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_comment.uid</code>.
     */
    public UInteger getUid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.community_comment.body</code>.
     */
    public void setBody(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_comment.body</code>.
     */
    public String getBody() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.community_comment.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_comment.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.community_comment.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_comment.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return CommunityComment.COMMUNITY_COMMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return CommunityComment.COMMUNITY_COMMENT.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CommunityComment.COMMUNITY_COMMENT.BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return CommunityComment.COMMUNITY_COMMENT.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return CommunityComment.COMMUNITY_COMMENT.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityCommentRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityCommentRecord value2(UInteger value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityCommentRecord value3(String value) {
        setBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityCommentRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityCommentRecord value5(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityCommentRecord values(UInteger value1, UInteger value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommunityCommentRecord
     */
    public CommunityCommentRecord() {
        super(CommunityComment.COMMUNITY_COMMENT);
    }

    /**
     * Create a detached, initialised CommunityCommentRecord
     */
    public CommunityCommentRecord(UInteger id, UInteger uid, String body, LocalDateTime created, LocalDateTime updated) {
        super(CommunityComment.COMMUNITY_COMMENT);

        set(0, id);
        set(1, uid);
        set(2, body);
        set(3, created);
        set(4, updated);
    }
}
