/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.CommunityContent;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * 커뮤니티 게시글
 *  - 현재 사용안함
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommunityContentRecord extends UpdatableRecordImpl<CommunityContentRecord> implements Record11<UInteger, UInteger, String, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1564731339;

    /**
     * Setter for <code>fishing_reservation.community_content.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.uid</code>.
     */
    public void setUid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.uid</code>.
     */
    public UInteger getUid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.body</code>.
     */
    public void setBody(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.body</code>.
     */
    public String getBody() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.anonymous</code>.
     */
    public void setAnonymous(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.anonymous</code>.
     */
    public UInteger getAnonymous() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.good</code>.
     */
    public void setGood(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.good</code>.
     */
    public UInteger getGood() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.bad</code>.
     */
    public void setBad(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.bad</code>.
     */
    public UInteger getBad() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.comments</code>.
     */
    public void setComments(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.comments</code>.
     */
    public UInteger getComments() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.deleted</code>.
     */
    public void setDeleted(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.deleted</code>.
     */
    public UInteger getDeleted() {
        return (UInteger) get(7);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.reported</code>.
     */
    public void setReported(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.reported</code>.
     */
    public UInteger getReported() {
        return (UInteger) get(8);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>fishing_reservation.community_content.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>fishing_reservation.community_content.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<UInteger, UInteger, String, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<UInteger, UInteger, String, UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return CommunityContent.COMMUNITY_CONTENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return CommunityContent.COMMUNITY_CONTENT.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CommunityContent.COMMUNITY_CONTENT.BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return CommunityContent.COMMUNITY_CONTENT.ANONYMOUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return CommunityContent.COMMUNITY_CONTENT.GOOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return CommunityContent.COMMUNITY_CONTENT.BAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return CommunityContent.COMMUNITY_CONTENT.COMMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field8() {
        return CommunityContent.COMMUNITY_CONTENT.DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field9() {
        return CommunityContent.COMMUNITY_CONTENT.REPORTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return CommunityContent.COMMUNITY_CONTENT.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return CommunityContent.COMMUNITY_CONTENT.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component4() {
        return getAnonymous();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component5() {
        return getGood();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component6() {
        return getBad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component7() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component8() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component9() {
        return getReported();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getAnonymous();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getGood();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getBad();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getComments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value8() {
        return getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value9() {
        return getReported();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value2(UInteger value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value3(String value) {
        setBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value4(UInteger value) {
        setAnonymous(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value5(UInteger value) {
        setGood(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value6(UInteger value) {
        setBad(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value7(UInteger value) {
        setComments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value8(UInteger value) {
        setDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value9(UInteger value) {
        setReported(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value10(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord value11(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommunityContentRecord values(UInteger value1, UInteger value2, String value3, UInteger value4, UInteger value5, UInteger value6, UInteger value7, UInteger value8, UInteger value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommunityContentRecord
     */
    public CommunityContentRecord() {
        super(CommunityContent.COMMUNITY_CONTENT);
    }

    /**
     * Create a detached, initialised CommunityContentRecord
     */
    public CommunityContentRecord(UInteger id, UInteger uid, String body, UInteger anonymous, UInteger good, UInteger bad, UInteger comments, UInteger deleted, UInteger reported, LocalDateTime created, LocalDateTime updated) {
        super(CommunityContent.COMMUNITY_CONTENT);

        set(0, id);
        set(1, uid);
        set(2, body);
        set(3, anonymous);
        set(4, good);
        set(5, bad);
        set(6, comments);
        set(7, deleted);
        set(8, reported);
        set(9, created);
        set(10, updated);
    }
}
