/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.FishingEnvironment;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FishingEnvironmentRecord extends UpdatableRecordImpl<FishingEnvironmentRecord> implements Record6<String, String, Integer, LocalDateTime, LocalDateTime, String> {

    private static final long serialVersionUID = 396820242;

    /**
     * Setter for <code>fishing_reservation.fishing_environment.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.fishing_environment.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.fishing_environment.property</code>.
     */
    public void setProperty(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.fishing_environment.property</code>.
     */
    public String getProperty() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.fishing_environment.app_id</code>.
     */
    public void setAppId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.fishing_environment.app_id</code>.
     */
    public Integer getAppId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.fishing_environment.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.fishing_environment.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.fishing_environment.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.fishing_environment.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fishing_reservation.fishing_environment.use_yn</code>.
     */
    public void setUseYn(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fishing_reservation.fishing_environment.use_yn</code>.
     */
    public String getUseYn() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, LocalDateTime, LocalDateTime, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Integer, LocalDateTime, LocalDateTime, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return FishingEnvironment.FISHING_ENVIRONMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FishingEnvironment.FISHING_ENVIRONMENT.PROPERTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return FishingEnvironment.FISHING_ENVIRONMENT.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return FishingEnvironment.FISHING_ENVIRONMENT.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return FishingEnvironment.FISHING_ENVIRONMENT.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FishingEnvironment.FISHING_ENVIRONMENT.USE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProperty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProperty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FishingEnvironmentRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FishingEnvironmentRecord value2(String value) {
        setProperty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FishingEnvironmentRecord value3(Integer value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FishingEnvironmentRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FishingEnvironmentRecord value5(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FishingEnvironmentRecord value6(String value) {
        setUseYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FishingEnvironmentRecord values(String value1, String value2, Integer value3, LocalDateTime value4, LocalDateTime value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FishingEnvironmentRecord
     */
    public FishingEnvironmentRecord() {
        super(FishingEnvironment.FISHING_ENVIRONMENT);
    }

    /**
     * Create a detached, initialised FishingEnvironmentRecord
     */
    public FishingEnvironmentRecord(String id, String property, Integer appId, LocalDateTime created, LocalDateTime updated, String useYn) {
        super(FishingEnvironment.FISHING_ENVIRONMENT);

        set(0, id);
        set(1, property);
        set(2, appId);
        set(3, created);
        set(4, updated);
        set(5, useYn);
    }
}
