/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.MyNews;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyNewsRecord extends UpdatableRecordImpl<MyNewsRecord> implements Record9<Integer, Integer, Integer, String, String, LocalDateTime, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1173189170;

    /**
     * Setter for <code>fishing_reservation.my_news.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.my_news.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.my_news.app_id</code>.
     */
    public void setAppId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.my_news.app_id</code>.
     */
    public Integer getAppId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.my_news.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.my_news.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.my_news.message</code>.
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.my_news.message</code>.
     */
    public String getMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.my_news.route</code>.
     */
    public void setRoute(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.my_news.route</code>.
     */
    public String getRoute() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fishing_reservation.my_news.confirm_date</code>.
     */
    public void setConfirmDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>fishing_reservation.my_news.confirm_date</code>.
     */
    public LocalDateTime getConfirmDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>fishing_reservation.my_news.use_yn</code>.
     */
    public void setUseYn(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fishing_reservation.my_news.use_yn</code>.
     */
    public String getUseYn() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fishing_reservation.my_news.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>fishing_reservation.my_news.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>fishing_reservation.my_news.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>fishing_reservation.my_news.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, LocalDateTime, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, LocalDateTime, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MyNews.MY_NEWS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MyNews.MY_NEWS.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MyNews.MY_NEWS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MyNews.MY_NEWS.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MyNews.MY_NEWS.ROUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return MyNews.MY_NEWS.CONFIRM_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MyNews.MY_NEWS.USE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return MyNews.MY_NEWS.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return MyNews.MY_NEWS.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRoute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getConfirmDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component9() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRoute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getConfirmDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord value2(Integer value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord value4(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord value5(String value) {
        setRoute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord value6(LocalDateTime value) {
        setConfirmDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord value7(String value) {
        setUseYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord value8(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord value9(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyNewsRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, LocalDateTime value6, String value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MyNewsRecord
     */
    public MyNewsRecord() {
        super(MyNews.MY_NEWS);
    }

    /**
     * Create a detached, initialised MyNewsRecord
     */
    public MyNewsRecord(Integer id, Integer appId, Integer userId, String message, String route, LocalDateTime confirmDate, String useYn, LocalDateTime updated, LocalDateTime created) {
        super(MyNews.MY_NEWS);

        set(0, id);
        set(1, appId);
        set(2, userId);
        set(3, message);
        set(4, route);
        set(5, confirmDate);
        set(6, useYn);
        set(7, updated);
        set(8, created);
    }
}
