/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.ReservationHistory;
import com.google.gson.JsonElement;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReservationHistoryRecord extends UpdatableRecordImpl<ReservationHistoryRecord> implements Record22<Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, String, String, String, LocalDateTime, String, String, String, String, String, LocalDateTime, JsonElement, Integer, LocalDateTime> {

    private static final long serialVersionUID = -2025872715;

    /**
     * Setter for <code>fishing_reservation.reservation_history.reservation_id</code>.
     */
    public void setReservationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.reservation_id</code>.
     */
    public Integer getReservationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.seq</code>.
     */
    public void setSeq(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.seq</code>.
     */
    public Integer getSeq() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.crud</code>.
     */
    public void setCrud(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.crud</code>.
     */
    public String getCrud() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.app_id</code>.
     */
    public void setAppId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.app_id</code>.
     */
    public Integer getAppId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.schedule_id</code>.
     */
    public void setScheduleId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.schedule_id</code>.
     */
    public Integer getScheduleId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.type</code>.
     */
    public void setType(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.type</code>.
     */
    public Integer getType() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.person_count</code>.
     */
    public void setPersonCount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.person_count</code>.
     */
    public Integer getPersonCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.price</code>.
     */
    public void setPrice(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.status</code>. (STATUS)
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.status</code>. (STATUS)
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.deposit_status</code>. (DEPOSIT_STATUS)
     */
    public void setDepositStatus(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.deposit_status</code>. (DEPOSIT_STATUS)
     */
    public String getDepositStatus() {
        return (String) get(10);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.depositor</code>.
     */
    public void setDepositor(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.depositor</code>.
     */
    public String getDepositor() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.deposit_deadline</code>.
     */
    public void setDepositDeadline(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.deposit_deadline</code>.
     */
    public LocalDateTime getDepositDeadline() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.request_remarks</code>.
     */
    public void setRequestRemarks(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.request_remarks</code>.
     */
    public String getRequestRemarks() {
        return (String) get(13);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.remarks</code>.
     */
    public void setRemarks(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(14);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.use_yn</code>.
     */
    public void setUseYn(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.use_yn</code>.
     */
    public String getUseYn() {
        return (String) get(15);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.cancel_code</code>.
     */
    public void setCancelCode(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.cancel_code</code>.
     */
    public String getCancelCode() {
        return (String) get(16);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.cancel_reason</code>.
     */
    public void setCancelReason(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.cancel_reason</code>.
     */
    public String getCancelReason() {
        return (String) get(17);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.cancel_date</code>.
     */
    public void setCancelDate(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.cancel_date</code>.
     */
    public LocalDateTime getCancelDate() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.push_type</code>.
     */
    public void setPushType(JsonElement value) {
        set(19, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.push_type</code>.
     */
    public JsonElement getPushType() {
        return (JsonElement) get(19);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.work_id</code>.
     */
    public void setWorkId(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.work_id</code>.
     */
    public Integer getWorkId() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_history.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_history.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, String, String, String, LocalDateTime, String, String, String, String, String, LocalDateTime, JsonElement, Integer, LocalDateTime> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Integer, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, String, String, String, LocalDateTime, String, String, String, String, String, LocalDateTime, JsonElement, Integer, LocalDateTime> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ReservationHistory.RESERVATION_HISTORY.RESERVATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ReservationHistory.RESERVATION_HISTORY.SEQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ReservationHistory.RESERVATION_HISTORY.CRUD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ReservationHistory.RESERVATION_HISTORY.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ReservationHistory.RESERVATION_HISTORY.SCHEDULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ReservationHistory.RESERVATION_HISTORY.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ReservationHistory.RESERVATION_HISTORY.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return ReservationHistory.RESERVATION_HISTORY.PERSON_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return ReservationHistory.RESERVATION_HISTORY.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return ReservationHistory.RESERVATION_HISTORY.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return ReservationHistory.RESERVATION_HISTORY.DEPOSIT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ReservationHistory.RESERVATION_HISTORY.DEPOSITOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return ReservationHistory.RESERVATION_HISTORY.DEPOSIT_DEADLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return ReservationHistory.RESERVATION_HISTORY.REQUEST_REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return ReservationHistory.RESERVATION_HISTORY.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return ReservationHistory.RESERVATION_HISTORY.USE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return ReservationHistory.RESERVATION_HISTORY.CANCEL_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return ReservationHistory.RESERVATION_HISTORY.CANCEL_REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field19() {
        return ReservationHistory.RESERVATION_HISTORY.CANCEL_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JsonElement> field20() {
        return ReservationHistory.RESERVATION_HISTORY.PUSH_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field21() {
        return ReservationHistory.RESERVATION_HISTORY.WORK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field22() {
        return ReservationHistory.RESERVATION_HISTORY.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getReservationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSeq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCrud();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getPersonCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDepositStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getDepositor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component13() {
        return getDepositDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getRequestRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getCancelCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getCancelReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component19() {
        return getCancelDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonElement component20() {
        return getPushType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component21() {
        return getWorkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component22() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getReservationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSeq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCrud();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPersonCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDepositStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDepositor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getDepositDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getRequestRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getCancelCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getCancelReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value19() {
        return getCancelDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonElement value20() {
        return getPushType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value21() {
        return getWorkId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value22() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value1(Integer value) {
        setReservationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value2(Integer value) {
        setSeq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value3(String value) {
        setCrud(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value4(Integer value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value5(Integer value) {
        setScheduleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value6(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value7(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value8(Integer value) {
        setPersonCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value9(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value10(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value11(String value) {
        setDepositStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value12(String value) {
        setDepositor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value13(LocalDateTime value) {
        setDepositDeadline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value14(String value) {
        setRequestRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value15(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value16(String value) {
        setUseYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value17(String value) {
        setCancelCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value18(String value) {
        setCancelReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value19(LocalDateTime value) {
        setCancelDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value20(JsonElement value) {
        setPushType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value21(Integer value) {
        setWorkId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord value22(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationHistoryRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, String value10, String value11, String value12, LocalDateTime value13, String value14, String value15, String value16, String value17, String value18, LocalDateTime value19, JsonElement value20, Integer value21, LocalDateTime value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationHistoryRecord
     */
    public ReservationHistoryRecord() {
        super(ReservationHistory.RESERVATION_HISTORY);
    }

    /**
     * Create a detached, initialised ReservationHistoryRecord
     */
    public ReservationHistoryRecord(Integer reservationId, Integer seq, String crud, Integer appId, Integer scheduleId, Integer userId, Integer type, Integer personCount, Integer price, String status, String depositStatus, String depositor, LocalDateTime depositDeadline, String requestRemarks, String remarks, String useYn, String cancelCode, String cancelReason, LocalDateTime cancelDate, JsonElement pushType, Integer workId, LocalDateTime created) {
        super(ReservationHistory.RESERVATION_HISTORY);

        set(0, reservationId);
        set(1, seq);
        set(2, crud);
        set(3, appId);
        set(4, scheduleId);
        set(5, userId);
        set(6, type);
        set(7, personCount);
        set(8, price);
        set(9, status);
        set(10, depositStatus);
        set(11, depositor);
        set(12, depositDeadline);
        set(13, requestRemarks);
        set(14, remarks);
        set(15, useYn);
        set(16, cancelCode);
        set(17, cancelReason);
        set(18, cancelDate);
        set(19, pushType);
        set(20, workId);
        set(21, created);
    }
}
