/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.ReservationWaiting;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * 예약대기 관리
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReservationWaitingRecord extends TableRecordImpl<ReservationWaitingRecord> implements Record11<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1104557061;

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.app_id</code>.
     */
    public void setAppId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.app_id</code>.
     */
    public Integer getAppId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.reservation_id</code>.
     */
    public void setReservationId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.reservation_id</code>.
     */
    public Integer getReservationId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.schedule_id</code>.
     */
    public void setScheduleId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.schedule_id</code>.
     */
    public Integer getScheduleId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.status</code>. 1:미입금 2:입금완료(개발예정) 3:예약상태로 변경 4:사용자취소
     */
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.status</code>. 1:미입금 2:입금완료(개발예정) 3:예약상태로 변경 4:사용자취소
     */
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.person_count</code>.
     */
    public void setPersonCount(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.person_count</code>.
     */
    public Integer getPersonCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.use_yn</code>.
     */
    public void setUseYn(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.use_yn</code>.
     */
    public Integer getUseYn() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.cancle_date</code>.
     */
    public void setCancleDate(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.cancle_date</code>.
     */
    public Integer getCancleDate() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>fishing_reservation.reservation_waiting.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation_waiting.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ReservationWaiting.RESERVATION_WAITING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ReservationWaiting.RESERVATION_WAITING.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ReservationWaiting.RESERVATION_WAITING.RESERVATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ReservationWaiting.RESERVATION_WAITING.SCHEDULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ReservationWaiting.RESERVATION_WAITING.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ReservationWaiting.RESERVATION_WAITING.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ReservationWaiting.RESERVATION_WAITING.PERSON_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return ReservationWaiting.RESERVATION_WAITING.USE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return ReservationWaiting.RESERVATION_WAITING.CANCLE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return ReservationWaiting.RESERVATION_WAITING.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return ReservationWaiting.RESERVATION_WAITING.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getReservationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getPersonCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getCancleDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getReservationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPersonCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCancleDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value2(Integer value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value3(Integer value) {
        setReservationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value4(Integer value) {
        setScheduleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value5(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value7(Integer value) {
        setPersonCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value8(Integer value) {
        setUseYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value9(Integer value) {
        setCancleDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value10(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord value11(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationWaitingRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationWaitingRecord
     */
    public ReservationWaitingRecord() {
        super(ReservationWaiting.RESERVATION_WAITING);
    }

    /**
     * Create a detached, initialised ReservationWaitingRecord
     */
    public ReservationWaitingRecord(Integer id, Integer appId, Integer reservationId, Integer scheduleId, Integer userId, Integer status, Integer personCount, Integer useYn, Integer cancleDate, LocalDateTime updated, LocalDateTime created) {
        super(ReservationWaiting.RESERVATION_WAITING);

        set(0, id);
        set(1, appId);
        set(2, reservationId);
        set(3, scheduleId);
        set(4, userId);
        set(5, status);
        set(6, personCount);
        set(7, useYn);
        set(8, cancleDate);
        set(9, updated);
        set(10, created);
    }
}
