/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.Reservation;
import com.google.gson.JsonElement;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 예약 관리
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReservationRecord extends UpdatableRecordImpl<ReservationRecord> implements Record20<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, String, LocalDateTime, String, String, String, String, String, LocalDateTime, JsonElement, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1558529280;

    /**
     * Setter for <code>fishing_reservation.reservation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.app_id</code>.
     */
    public void setAppId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.app_id</code>.
     */
    public Integer getAppId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.schedule_id</code>.
     */
    public void setScheduleId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.schedule_id</code>.
     */
    public Integer getScheduleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.type</code>. 예약타입(1: 개인, 2: 단체, 3: 대여)
단체(2) - 사용자 1명이 여러사람을 예약
대여(3) - 사용자 2명이 배를 대여함, 추가 예약 불가
     */
    public void setType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.type</code>. 예약타입(1: 개인, 2: 단체, 3: 대여)
단체(2) - 사용자 1명이 여러사람을 예약
대여(3) - 사용자 2명이 배를 대여함, 추가 예약 불가
     */
    public Integer getType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.person_count</code>.
     */
    public void setPersonCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.person_count</code>.
     */
    public Integer getPersonCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.price</code>. type, person_count 에 따라 계산된 금액
     */
    public void setPrice(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.price</code>. type, person_count 에 따라 계산된 금액
     */
    public Integer getPrice() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.status</code>. (STATUS)
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.status</code>. (STATUS)
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.deposit_status</code>. (DEPOSIT_STATUS)
     */
    public void setDepositStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.deposit_status</code>. (DEPOSIT_STATUS)
     */
    public String getDepositStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.depositor</code>.
     */
    public void setDepositor(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.depositor</code>.
     */
    public String getDepositor() {
        return (String) get(9);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.deposit_deadline</code>.
     */
    public void setDepositDeadline(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.deposit_deadline</code>.
     */
    public LocalDateTime getDepositDeadline() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.request_remarks</code>.
     */
    public void setRequestRemarks(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.request_remarks</code>.
     */
    public String getRequestRemarks() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.remarks</code>.
     */
    public void setRemarks(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.use_yn</code>.
     */
    public void setUseYn(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.use_yn</code>.
     */
    public String getUseYn() {
        return (String) get(13);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.cancel_code</code>. 0: 사용자취소, 1:관리자취소, 2:미입금
     */
    public void setCancelCode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.cancel_code</code>. 0: 사용자취소, 1:관리자취소, 2:미입금
     */
    public String getCancelCode() {
        return (String) get(14);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.cancel_reason</code>.
     */
    public void setCancelReason(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.cancel_reason</code>.
     */
    public String getCancelReason() {
        return (String) get(15);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.cancel_date</code>.
     */
    public void setCancelDate(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.cancel_date</code>.
     */
    public LocalDateTime getCancelDate() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.push_type</code>.
     */
    public void setPushType(JsonElement value) {
        set(17, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.push_type</code>.
     */
    public JsonElement getPushType() {
        return (JsonElement) get(17);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>fishing_reservation.reservation.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>fishing_reservation.reservation.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, String, LocalDateTime, String, String, String, String, String, LocalDateTime, JsonElement, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, String, String, LocalDateTime, String, String, String, String, String, LocalDateTime, JsonElement, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Reservation.RESERVATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Reservation.RESERVATION.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Reservation.RESERVATION.SCHEDULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Reservation.RESERVATION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Reservation.RESERVATION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Reservation.RESERVATION.PERSON_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Reservation.RESERVATION.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Reservation.RESERVATION.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Reservation.RESERVATION.DEPOSIT_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Reservation.RESERVATION.DEPOSITOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return Reservation.RESERVATION.DEPOSIT_DEADLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Reservation.RESERVATION.REQUEST_REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Reservation.RESERVATION.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Reservation.RESERVATION.USE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Reservation.RESERVATION.CANCEL_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Reservation.RESERVATION.CANCEL_REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field17() {
        return Reservation.RESERVATION.CANCEL_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JsonElement> field18() {
        return Reservation.RESERVATION.PUSH_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field19() {
        return Reservation.RESERVATION.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field20() {
        return Reservation.RESERVATION.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getPersonCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDepositStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getDepositor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getDepositDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getRequestRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getCancelCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getCancelReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component17() {
        return getCancelDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonElement component18() {
        return getPushType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component19() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component20() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getScheduleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPersonCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDepositStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDepositor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getDepositDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getRequestRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getCancelCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getCancelReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value17() {
        return getCancelDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonElement value18() {
        return getPushType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value19() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value20() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value2(Integer value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value3(Integer value) {
        setScheduleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value4(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value5(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value6(Integer value) {
        setPersonCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value7(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value8(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value9(String value) {
        setDepositStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value10(String value) {
        setDepositor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value11(LocalDateTime value) {
        setDepositDeadline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value12(String value) {
        setRequestRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value13(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value14(String value) {
        setUseYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value15(String value) {
        setCancelCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value16(String value) {
        setCancelReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value17(LocalDateTime value) {
        setCancelDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value18(JsonElement value) {
        setPushType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value19(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord value20(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReservationRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, String value8, String value9, String value10, LocalDateTime value11, String value12, String value13, String value14, String value15, String value16, LocalDateTime value17, JsonElement value18, LocalDateTime value19, LocalDateTime value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationRecord
     */
    public ReservationRecord() {
        super(Reservation.RESERVATION);
    }

    /**
     * Create a detached, initialised ReservationRecord
     */
    public ReservationRecord(Integer id, Integer appId, Integer scheduleId, Integer userId, Integer type, Integer personCount, Integer price, String status, String depositStatus, String depositor, LocalDateTime depositDeadline, String requestRemarks, String remarks, String useYn, String cancelCode, String cancelReason, LocalDateTime cancelDate, JsonElement pushType, LocalDateTime updated, LocalDateTime created) {
        super(Reservation.RESERVATION);

        set(0, id);
        set(1, appId);
        set(2, scheduleId);
        set(3, userId);
        set(4, type);
        set(5, personCount);
        set(6, price);
        set(7, status);
        set(8, depositStatus);
        set(9, depositor);
        set(10, depositDeadline);
        set(11, requestRemarks);
        set(12, remarks);
        set(13, useYn);
        set(14, cancelCode);
        set(15, cancelReason);
        set(16, cancelDate);
        set(17, pushType);
        set(18, updated);
        set(19, created);
    }
}
