/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq.tables.records;


import com.ddastudio.fishing.jooq.tables.User;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 사용자 관리
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record17<Integer, String, String, Integer, String, String, String, String, String, LocalDateTime, String, String, String, LocalDateTime, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1361887828;

    /**
     * Setter for <code>fishing_reservation.user.id</code>. 사용자 아이디
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.id</code>. 사용자 아이디
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>fishing_reservation.user.name</code>. 사용자 이름
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.name</code>. 사용자 이름
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fishing_reservation.user.avatar</code>.
     */
    public void setAvatar(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fishing_reservation.user.app_id</code>. 앱 아이디
     */
    public void setAppId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.app_id</code>. 앱 아이디
     */
    public Integer getAppId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fishing_reservation.user.role</code>. customer: 일반사용자, manager: 관리자, admin: 운영자(개발자)
     */
    public void setRole(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.role</code>. customer: 일반사용자, manager: 관리자, admin: 운영자(개발자)
     */
    public String getRole() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fishing_reservation.user.captain_yn</code>.
     */
    public void setCaptainYn(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.captain_yn</code>.
     */
    public String getCaptainYn() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fishing_reservation.user.provider</code>.
     */
    public void setProvider(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.provider</code>.
     */
    public String getProvider() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fishing_reservation.user.provider_uid</code>.
     */
    public void setProviderUid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.provider_uid</code>.
     */
    public String getProviderUid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fishing_reservation.user.use_yn</code>. 사용여부
     */
    public void setUseYn(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.use_yn</code>. 사용여부
     */
    public String getUseYn() {
        return (String) get(8);
    }

    /**
     * Setter for <code>fishing_reservation.user.cancel_date</code>.
     */
    public void setCancelDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.cancel_date</code>.
     */
    public LocalDateTime getCancelDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>fishing_reservation.user.email</code>.
     */
    public void setEmail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.email</code>.
     */
    public String getEmail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>fishing_reservation.user.pw</code>.
     */
    public void setPw(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.pw</code>.
     */
    public String getPw() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fishing_reservation.user.refresh_token</code>.
     */
    public void setRefreshToken(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.refresh_token</code>.
     */
    public String getRefreshToken() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fishing_reservation.user.email_check</code>.
     */
    public void setEmailCheck(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.email_check</code>.
     */
    public LocalDateTime getEmailCheck() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>fishing_reservation.user.push_token</code>.
     */
    public void setPushToken(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.push_token</code>.
     */
    public String getPushToken() {
        return (String) get(14);
    }

    /**
     * Setter for <code>fishing_reservation.user.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>fishing_reservation.user.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>fishing_reservation.user.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, String, Integer, String, String, String, String, String, LocalDateTime, String, String, String, LocalDateTime, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Integer, String, String, Integer, String, String, String, String, String, LocalDateTime, String, String, String, LocalDateTime, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return User.USER.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return User.USER.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return User.USER.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return User.USER.CAPTAIN_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return User.USER.PROVIDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return User.USER.PROVIDER_UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return User.USER.USE_YN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return User.USER.CANCEL_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return User.USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return User.USER.PW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return User.USER.REFRESH_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return User.USER.EMAIL_CHECK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return User.USER.PUSH_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field16() {
        return User.USER.UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field17() {
        return User.USER.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCaptainYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getProviderUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getCancelDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getPw();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getRefreshToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component14() {
        return getEmailCheck();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getPushToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component16() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component17() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCaptainYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getProvider();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getProviderUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUseYn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getCancelDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getPw();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getRefreshToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getEmailCheck();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getPushToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value16() {
        return getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value17() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(Integer value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(String value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(String value) {
        setCaptainYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(String value) {
        setProvider(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(String value) {
        setProviderUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value9(String value) {
        setUseYn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value10(LocalDateTime value) {
        setCancelDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value11(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value12(String value) {
        setPw(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value13(String value) {
        setRefreshToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value14(LocalDateTime value) {
        setEmailCheck(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value15(String value) {
        setPushToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value16(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value17(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, String value8, String value9, LocalDateTime value10, String value11, String value12, String value13, LocalDateTime value14, String value15, LocalDateTime value16, LocalDateTime value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String name, String avatar, Integer appId, String role, String captainYn, String provider, String providerUid, String useYn, LocalDateTime cancelDate, String email, String pw, String refreshToken, LocalDateTime emailCheck, String pushToken, LocalDateTime updated, LocalDateTime created) {
        super(User.USER);

        set(0, id);
        set(1, name);
        set(2, avatar);
        set(3, appId);
        set(4, role);
        set(5, captainYn);
        set(6, provider);
        set(7, providerUid);
        set(8, useYn);
        set(9, cancelDate);
        set(10, email);
        set(11, pw);
        set(12, refreshToken);
        set(13, emailCheck);
        set(14, pushToken);
        set(15, updated);
        set(16, created);
    }
}
