= Account REST API Guide
SANGMESSI;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 특정 부분만 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스
[[resources-account]]
== 사용자

사용자 리소스는 회원가입을 하거나 사용자 조회 , 수정, 삭제할때 사용한다.

[[resources-accounts-list]]
=== 사용자 목록 조회

`GET` 요청을 사용하여 서비스의 모든 사용자를 조회할 수 있다.

operation::get-accounts[snippets='http-request,curl-request,http-response,response-fields,links']

[[resources-account-get]]
=== 사용자 한건 조회

`GET` 요청을 사용해서 기존 사용자를 조회 할 수 있다.

operation::get-account[snippets='http-request,curl-request,http-response,response-fields,links']


[[resources-account-create]]
=== 사용자 등록

`POST` 요청을 사용해서 새 사용자를 생성 할 수 있다.

operation::create-account[snippets='request-fields,http-request,request-headers,curl-request,http-response,response-headers,response-fields,links']

[[resources-account-confirm]]
=== 사용자 등록확인

`PATCH` 요청을 사용해서 기존 사용자의 회원가입을 완료 할 수 있다.

operation::confirm-account[snippets='request-fields,http-request,request-headers,curl-request,http-response,response-headers,response-fields,links']


[[resources-account-update]]
=== 사용자 수정

`PUT` 요청을 사용해서 기존 사용자를 수정할 수 있다.

operation::update-account[snippets='request-fields,http-request,request-headers,curl-request,http-response,response-headers,response-fields,links']

[[resources-account-delete]]
=== 사용자 삭제

`DELETE` 요청을 사용해서 기존 사용자를 삭제할 수 있다.

operation::delete-account[snippets='http-request,curl-request,http-response,response-fields,links']

