/*
 * This file is generated by jOOQ.
 */
package com.ddastudio.fishing.jooq;


import com.ddastudio.fishing.jooq.tables.Account;
import com.ddastudio.fishing.jooq.tables.AppMaster;
import com.ddastudio.fishing.jooq.tables.BoatMaster;
import com.ddastudio.fishing.jooq.tables.CodeMaster;
import com.ddastudio.fishing.jooq.tables.CommunityContent;
import com.ddastudio.fishing.jooq.tables.FishMaster;
import com.ddastudio.fishing.jooq.tables.FishingEnvironment;
import com.ddastudio.fishing.jooq.tables.MyNews;
import com.ddastudio.fishing.jooq.tables.OauthClientDetails;
import com.ddastudio.fishing.jooq.tables.Reservation;
import com.ddastudio.fishing.jooq.tables.ReservationHistory;
import com.ddastudio.fishing.jooq.tables.Schedule;
import com.ddastudio.fishing.jooq.tables.TestMaster;
import com.ddastudio.fishing.jooq.tables.UsedRefreshToken;
import com.ddastudio.fishing.jooq.tables.User;
import com.ddastudio.fishing.jooq.tables.records.AccountRecord;
import com.ddastudio.fishing.jooq.tables.records.AppMasterRecord;
import com.ddastudio.fishing.jooq.tables.records.BoatMasterRecord;
import com.ddastudio.fishing.jooq.tables.records.CodeMasterRecord;
import com.ddastudio.fishing.jooq.tables.records.CommunityContentRecord;
import com.ddastudio.fishing.jooq.tables.records.FishMasterRecord;
import com.ddastudio.fishing.jooq.tables.records.FishingEnvironmentRecord;
import com.ddastudio.fishing.jooq.tables.records.MyNewsRecord;
import com.ddastudio.fishing.jooq.tables.records.OauthClientDetailsRecord;
import com.ddastudio.fishing.jooq.tables.records.ReservationHistoryRecord;
import com.ddastudio.fishing.jooq.tables.records.ReservationRecord;
import com.ddastudio.fishing.jooq.tables.records.ScheduleRecord;
import com.ddastudio.fishing.jooq.tables.records.TestMasterRecord;
import com.ddastudio.fishing.jooq.tables.records.UsedRefreshTokenRecord;
import com.ddastudio.fishing.jooq.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>fishing_reservation</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountRecord, Integer> IDENTITY_ACCOUNT = Identities0.IDENTITY_ACCOUNT;
    public static final Identity<AppMasterRecord, Integer> IDENTITY_APP_MASTER = Identities0.IDENTITY_APP_MASTER;
    public static final Identity<BoatMasterRecord, Integer> IDENTITY_BOAT_MASTER = Identities0.IDENTITY_BOAT_MASTER;
    public static final Identity<FishMasterRecord, Integer> IDENTITY_FISH_MASTER = Identities0.IDENTITY_FISH_MASTER;
    public static final Identity<MyNewsRecord, Integer> IDENTITY_MY_NEWS = Identities0.IDENTITY_MY_NEWS;
    public static final Identity<ReservationRecord, Integer> IDENTITY_RESERVATION = Identities0.IDENTITY_RESERVATION;
    public static final Identity<ScheduleRecord, Integer> IDENTITY_SCHEDULE = Identities0.IDENTITY_SCHEDULE;
    public static final Identity<TestMasterRecord, Integer> IDENTITY_TEST_MASTER = Identities0.IDENTITY_TEST_MASTER;
    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_PRIMARY = UniqueKeys0.KEY_ACCOUNT_PRIMARY;
    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_UK_3CHG059P7XVAFVSVRO01UBODQ = UniqueKeys0.KEY_ACCOUNT_UK_3CHG059P7XVAFVSVRO01UBODQ;
    public static final UniqueKey<AppMasterRecord> KEY_APP_MASTER_PRIMARY = UniqueKeys0.KEY_APP_MASTER_PRIMARY;
    public static final UniqueKey<BoatMasterRecord> KEY_BOAT_MASTER_PRIMARY = UniqueKeys0.KEY_BOAT_MASTER_PRIMARY;
    public static final UniqueKey<CodeMasterRecord> KEY_CODE_MASTER_CODE_MASTER_PK = UniqueKeys0.KEY_CODE_MASTER_CODE_MASTER_PK;
    public static final UniqueKey<CommunityContentRecord> KEY_COMMUNITY_CONTENT_PRIMARY = UniqueKeys0.KEY_COMMUNITY_CONTENT_PRIMARY;
    public static final UniqueKey<FishMasterRecord> KEY_FISH_MASTER_FISH_MASTER_ID_UINDEX = UniqueKeys0.KEY_FISH_MASTER_FISH_MASTER_ID_UINDEX;
    public static final UniqueKey<FishingEnvironmentRecord> KEY_FISHING_ENVIRONMENT_PRIMARY = UniqueKeys0.KEY_FISHING_ENVIRONMENT_PRIMARY;
    public static final UniqueKey<MyNewsRecord> KEY_MY_NEWS_PRIMARY = UniqueKeys0.KEY_MY_NEWS_PRIMARY;
    public static final UniqueKey<OauthClientDetailsRecord> KEY_OAUTH_CLIENT_DETAILS_PRIMARY = UniqueKeys0.KEY_OAUTH_CLIENT_DETAILS_PRIMARY;
    public static final UniqueKey<ReservationRecord> KEY_RESERVATION_PRIMARY = UniqueKeys0.KEY_RESERVATION_PRIMARY;
    public static final UniqueKey<ReservationHistoryRecord> KEY_RESERVATION_HISTORY_PRIMARY = UniqueKeys0.KEY_RESERVATION_HISTORY_PRIMARY;
    public static final UniqueKey<ScheduleRecord> KEY_SCHEDULE_PRIMARY = UniqueKeys0.KEY_SCHEDULE_PRIMARY;
    public static final UniqueKey<ScheduleRecord> KEY_SCHEDULE_APP_ID = UniqueKeys0.KEY_SCHEDULE_APP_ID;
    public static final UniqueKey<TestMasterRecord> KEY_TEST_MASTER_PRIMARY = UniqueKeys0.KEY_TEST_MASTER_PRIMARY;
    public static final UniqueKey<UsedRefreshTokenRecord> KEY_USED_REFRESH_TOKEN_PRIMARY = UniqueKeys0.KEY_USED_REFRESH_TOKEN_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AccountRecord, Integer> IDENTITY_ACCOUNT = Internal.createIdentity(Account.ACCOUNT, Account.ACCOUNT.ID);
        public static Identity<AppMasterRecord, Integer> IDENTITY_APP_MASTER = Internal.createIdentity(AppMaster.APP_MASTER, AppMaster.APP_MASTER.ID);
        public static Identity<BoatMasterRecord, Integer> IDENTITY_BOAT_MASTER = Internal.createIdentity(BoatMaster.BOAT_MASTER, BoatMaster.BOAT_MASTER.ID);
        public static Identity<FishMasterRecord, Integer> IDENTITY_FISH_MASTER = Internal.createIdentity(FishMaster.FISH_MASTER, FishMaster.FISH_MASTER.ID);
        public static Identity<MyNewsRecord, Integer> IDENTITY_MY_NEWS = Internal.createIdentity(MyNews.MY_NEWS, MyNews.MY_NEWS.ID);
        public static Identity<ReservationRecord, Integer> IDENTITY_RESERVATION = Internal.createIdentity(Reservation.RESERVATION, Reservation.RESERVATION.ID);
        public static Identity<ScheduleRecord, Integer> IDENTITY_SCHEDULE = Internal.createIdentity(Schedule.SCHEDULE, Schedule.SCHEDULE.ID);
        public static Identity<TestMasterRecord, Integer> IDENTITY_TEST_MASTER = Internal.createIdentity(TestMaster.TEST_MASTER, TestMaster.TEST_MASTER.ID);
        public static Identity<UserRecord, Integer> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> KEY_ACCOUNT_PRIMARY = Internal.createUniqueKey(Account.ACCOUNT, "KEY_account_PRIMARY", Account.ACCOUNT.ID);
        public static final UniqueKey<AccountRecord> KEY_ACCOUNT_UK_3CHG059P7XVAFVSVRO01UBODQ = Internal.createUniqueKey(Account.ACCOUNT, "KEY_account_UK_3chg059p7xvafvsvro01ubodq", Account.ACCOUNT.PHONE_NO);
        public static final UniqueKey<AppMasterRecord> KEY_APP_MASTER_PRIMARY = Internal.createUniqueKey(AppMaster.APP_MASTER, "KEY_app_master_PRIMARY", AppMaster.APP_MASTER.ID);
        public static final UniqueKey<BoatMasterRecord> KEY_BOAT_MASTER_PRIMARY = Internal.createUniqueKey(BoatMaster.BOAT_MASTER, "KEY_boat_master_PRIMARY", BoatMaster.BOAT_MASTER.ID);
        public static final UniqueKey<CodeMasterRecord> KEY_CODE_MASTER_CODE_MASTER_PK = Internal.createUniqueKey(CodeMaster.CODE_MASTER, "KEY_code_master_code_master_pk", CodeMaster.CODE_MASTER.TYPE_CODE, CodeMaster.CODE_MASTER.CODE);
        public static final UniqueKey<CommunityContentRecord> KEY_COMMUNITY_CONTENT_PRIMARY = Internal.createUniqueKey(CommunityContent.COMMUNITY_CONTENT, "KEY_community_content_PRIMARY", CommunityContent.COMMUNITY_CONTENT.ID);
        public static final UniqueKey<FishMasterRecord> KEY_FISH_MASTER_FISH_MASTER_ID_UINDEX = Internal.createUniqueKey(FishMaster.FISH_MASTER, "KEY_fish_master_fish_master_id_uindex", FishMaster.FISH_MASTER.ID);
        public static final UniqueKey<FishingEnvironmentRecord> KEY_FISHING_ENVIRONMENT_PRIMARY = Internal.createUniqueKey(FishingEnvironment.FISHING_ENVIRONMENT, "KEY_fishing_environment_PRIMARY", FishingEnvironment.FISHING_ENVIRONMENT.ID);
        public static final UniqueKey<MyNewsRecord> KEY_MY_NEWS_PRIMARY = Internal.createUniqueKey(MyNews.MY_NEWS, "KEY_my_news_PRIMARY", MyNews.MY_NEWS.ID);
        public static final UniqueKey<OauthClientDetailsRecord> KEY_OAUTH_CLIENT_DETAILS_PRIMARY = Internal.createUniqueKey(OauthClientDetails.OAUTH_CLIENT_DETAILS, "KEY_oauth_client_details_PRIMARY", OauthClientDetails.OAUTH_CLIENT_DETAILS.CLIENT_ID);
        public static final UniqueKey<ReservationRecord> KEY_RESERVATION_PRIMARY = Internal.createUniqueKey(Reservation.RESERVATION, "KEY_reservation_PRIMARY", Reservation.RESERVATION.ID);
        public static final UniqueKey<ReservationHistoryRecord> KEY_RESERVATION_HISTORY_PRIMARY = Internal.createUniqueKey(ReservationHistory.RESERVATION_HISTORY, "KEY_reservation_history_PRIMARY", ReservationHistory.RESERVATION_HISTORY.RESERVATION_ID, ReservationHistory.RESERVATION_HISTORY.SEQ);
        public static final UniqueKey<ScheduleRecord> KEY_SCHEDULE_PRIMARY = Internal.createUniqueKey(Schedule.SCHEDULE, "KEY_schedule_PRIMARY", Schedule.SCHEDULE.ID);
        public static final UniqueKey<ScheduleRecord> KEY_SCHEDULE_APP_ID = Internal.createUniqueKey(Schedule.SCHEDULE, "KEY_schedule_app_id", Schedule.SCHEDULE.APP_ID, Schedule.SCHEDULE.BOAT_ID, Schedule.SCHEDULE.YYYYMMDD, Schedule.SCHEDULE.FROM_TIME);
        public static final UniqueKey<TestMasterRecord> KEY_TEST_MASTER_PRIMARY = Internal.createUniqueKey(TestMaster.TEST_MASTER, "KEY_test_master_PRIMARY", TestMaster.TEST_MASTER.ID);
        public static final UniqueKey<UsedRefreshTokenRecord> KEY_USED_REFRESH_TOKEN_PRIMARY = Internal.createUniqueKey(UsedRefreshToken.USED_REFRESH_TOKEN, "KEY_used_refresh_token_PRIMARY", UsedRefreshToken.USED_REFRESH_TOKEN.TOKEN);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }
}
